# Generated by Django 4.2 on 2025-05-25 13:36

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlightOffers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numberSeats', models.IntegerField()),
                ('dep_duration', models.TimeField()),
                ('arr_duration', models.TimeField(default=None)),
                ('currencyCode', models.CharField(max_length=3)),
                ('totalPrice', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='FlightRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('currencyCode', models.CharField(max_length=50)),
                ('originLocationCode', models.CharField(max_length=50)),
                ('destinationLocationCode', models.CharField(max_length=50)),
                ('departureDate', models.DateField()),
                ('departureTime', models.TimeField(default=datetime.time(10, 10, 10))),
                ('returnDate', models.DateField(blank=True, null=True)),
                ('adults', models.IntegerField()),
                ('children', models.IntegerField(blank=True, null=True)),
                ('infants', models.IntegerField(blank=True, null=True)),
                ('cabin', models.CharField(blank=True, max_length=20)),
                ('includedAirlines', models.CharField(blank=True, max_length=200)),
                ('excludedAirlines', models.CharField(blank=True, max_length=200)),
                ('travalClass', models.CharField(blank=True, max_length=50)),
                ('nonStop', models.BooleanField(default=False)),
                ('maxPrice', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('create_in', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FlightSegments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('there_seg', models.BooleanField()),
                ('dep_iataCode', models.CharField(max_length=3)),
                ('dep_terminal', models.CharField(max_length=2)),
                ('dep_dateTime', models.DateTimeField()),
                ('arr_iataCode', models.CharField(max_length=3)),
                ('arr_terminal', models.CharField(max_length=2)),
                ('arr_dateTime', models.DateTimeField()),
                ('carrierCode', models.CharField(max_length=2)),
                ('number', models.CharField(max_length=4)),
                ('aircraftCode', models.CharField(max_length=4)),
                ('operating', models.CharField(max_length=2)),
                ('duration', models.TimeField()),
                ('id_seg', models.CharField(max_length=2)),
                ('offer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightoffers')),
            ],
        ),
        migrations.AddField(
            model_name='flightoffers',
            name='flightRequest',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='flights.flightrequest'),
        ),
    ]
