# Generated by Django 4.2 on 2025-06-17 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flightrequest',
            name='cabin',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='excludedAirlines',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='includedAirlines',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='nonStop',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='travalClass',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
