# Generated by Django 4.2 on 2025-06-19 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0002_booking'),
    ]

    operations = [
        migrations.RenameField(
            model_name='flightrequest',
            old_name='travalClass',
            new_name='travelClass',
        ),
        migrations.AddField(
            model_name='flightoffer',
            name='adults_count',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='flightoffer',
            name='children_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='flightoffer',
            name='infants_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='flightrequest',
            name='adults',
            field=models.IntegerField(default=1),
        ),
    ]
