# Generated by Django 4.2 on 2025-06-30 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0004_iata_jsonbuffer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='iata',
            old_name='iata_code',
            new_name='iata',
        ),
        migrations.AddField(
            model_name='iata',
            name='city',
            field=models.CharField(default='city', max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='iata',
            name='state',
            field=models.CharField(default='state', max_length=50),
            preserve_default=False,
        ),
    ]
