# Generated by Django 4.2 on 2025-06-30 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flights', '0005_rename_iata_code_iata_iata_iata_city_iata_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iata',
            name='city',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iata',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='iata',
            name='state',
            field=models.CharField(max_length=100),
        ),
    ]
